# Terraform Docs
# https://github.com/terraform-docs/terraform-docs

formatter: markdown table
sections:
  show:
    - modules
    - providers
    - inputs
    - outputs
    - resources
sort:
  enabled: true
  by: required
settings:
  escape: false
  indent: 3
