name: Add or update team
description: Service interface for adding or updating a team in the Open Source Infrastructure (as Code) organization.
title: Add or update team
labels:
  - enhancement
  - good first issue

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following details to add or update a team in the Open Source Infrastructure (as Code) organization.

  - type: input
    id: email-address
    attributes:
      label: "Email address:"
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: true

  - type: input
    id: github-team-name
    attributes:
      label: "Team name:"
      description: This should follow the GitHub [naming conventions](https://docs.osinfra.io/product-guides/github/naming-conventions) and will be created if it does not exist.
      placeholder: stream-team-name
    validations:
      required: true

  - type: checkboxes
    id: role-repository-permissions
    attributes:
      label: "Team role and repository permissions:"
      description: Check the boxes that apply. You will be added to both by default if this is a new team.
      options:
        - label: "Team role: maintainer"
          required: false
        - label: "Repository permission: administrator"
          required: false

  - type: input
    id: github-username
    attributes:
      label: "Username:"
      description: This should be your GitHub username, not your email address.
      placeholder: octocat
    validations:
      required: true

  - type: textarea
    id: comments
    attributes:
      label: "Additional comments:"
      description: Anything else you'd like to add that would help us understand your request better?
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: "Code of conduct:"
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/osinfra-io/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
