name: GitHub Repository
description: Service interface for adding GitHub repositories to the organization
title: Add repository
labels:
  - enhancement
  - good first issue

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following details to request a new repository in the Open Source Infrastructure (as Code) organization.

  - type: input
    id: email-address
    attributes:
      label: "Email address:"
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: true

  - type: input
    id: github-team-name
    attributes:
      label: "Team name:"
      description: This should follow the GitHub [naming conventions](https://docs.osinfra.io/github/naming-conventions) and will be created if it does not exist.
      placeholder: stream-aligned-team-name
    validations:
      required: true

  - type: input
    id: github-repository-name
    attributes:
      label: "Repository name:"
      description: This should follow the GitHub [naming conventions](https://docs.osinfra.io/github/naming-conventions).
      placeholder: prefix-repository-name
    validations:
      required: true

  - type: input
    id: github-repository-description
    attributes:
      label: "Describe your repository:"
      description: Describe your repository in a few words.
      placeholder: This repository is for ...
    validations:
      required: true

  - type: input
    id: github-repository-topics
    attributes:
      label: "Topics:"
      description: Add topics to your repository. This will help others find your repository.
      placeholder: terraform, github-actions, ...
    validations:
      required: false

  - type: input
    id: github-repository-template
    attributes:
      label: "Template repository:"
      description: This will create a new repository from a template repository.
      placeholder: template-repository-name
    validations:
      required: false

  - type: checkboxes
    id: github-branch-protection
    attributes:
      label: "Disable branch protection:"
      description: This will disable branch protection for the repository. This is useful for repositories that are used for testing or other non-important purposes.
      options:
        - label: "True"
          required: false

  - type: textarea
    id: comments
    attributes:
     label: "Additional comments:"
     description: Anything else you'd like to add that would help us understand your request better?
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: "Code of conduct:"
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/osinfra-io/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
