name: GitHub Membership
description: Service interface for adding GitHub members to the organization
title: Add member
labels:
  - enhancement
  - good first issue

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following details to request membership to the Open Source Infrastructure (as Code) organization.

  - type: input
    id: email-address
    attributes:
      label: "Email address:"
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: true

  - type: input
    id: github-team-name
    attributes:
      label: "Team name:"
      description: This should follow the GitHub [naming conventions](https://docs.osinfra.io/github/naming-conventions) and will be created if it does not exist.
      placeholder: stream-aligned-team-name
    validations:
      required: true

  - type: checkboxes
    id: role
    attributes:
      label: "Team maintainer:"
      description: Check here if you would like to be maintainer of the team and received approval by an existing maintainer. You will be added by default if this is a new team.
      options:
        - label: Team maintainer
          required: false

  - type: checkboxes
    id: repository-admin
    attributes:
      label: "Repository Administrator:"
      description: Check here if you would like to be an administrator of the team and received approval by an existing administrator. You will be added by default if this is a new team.
      options:
        - label: Team maintainer
          required: false

  - type: input
    id: github-username
    attributes:
      label: "Username:"
      description: This should be your GitHub username, not your email address.
      placeholder: octocat
    validations:
      required: true

  - type: textarea
    id: comments
    attributes:
     label: "Additional comments:"
     description: Anything else you'd like to add that would help us understand your request better?
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: "Code of Conduct:"
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/osinfra-io/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
