name: Production

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  global_infra:
    name: "Global"
    uses: osinfra-io/github-terraform-called-workflows/.github/workflows/gcp-plan-and-apply.yml@main
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Production Infrastructure: Global"
      service_account: organization-github-actions@shared-terraform-tfa8-prod.iam.gserviceaccount.com
      terraform_state_bucket: shared-terraform-tfa8-prod-organization
      terraform_version: 1.3.7
      terraform_workspace: global-production
      workload_identity_provider: projects/680727702081/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      terraform_plan_secret_args: -var="github_token=${{ secrets.ORGANIZATION_MANAGEMENT_WORKFLOW }}"
