name: Production

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

# For reusable workflows, the permissions setting for id-token should be set to write at the
# caller workflow level or in the specific job that calls the reusable workflow.

permissions:
  contents: read
  id-token: write

jobs:
  main:
    name: "Main"
    uses: osinfra-io/github-opentofu-gcp-called-workflows/.github/workflows/plan-and-apply.yml@e3c59e43f2458550c7f13b6369fb6978b6f42c6e # v0.2.9
    if: github.actor != 'osinfra-sa'
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Production: Main"
      service_account: plt-gh-organization-github@plt-lz-backend-tf5f-prod.iam.gserviceaccount.com
      opentofu_kms_encryption_key: projects/plt-lz-backend-tf5f-prod/locations/us/keyRings/state-encryption/cryptoKeys/default
      opentofu_plan_args: -var-file=tfvars/production.tfvars
      opentofu_state_bucket: plt-gh-organization-d3c2-prod
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
      opentofu_workspace: main-production
      workload_identity_provider: projects/134040294660/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      opentofu_plan_secret_args: >-
        -var=token=${{ secrets.TOKEN }}
        -var=datadog_webhook_api_key=${{ secrets.DATADOG_WEBHOOK_API_KEY }}
        -var=discord_webhook_api_key=${{ secrets.DISCORD_WEBHOOK_API_KEY }}
